name: CI

on: [push]

jobs:
  build-incremental-updater:
    name: Build the application for incremental-updater
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: incremental-updater
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run lint && npm run prettier

  build-full-ingestion:
    name: Build the application for full-ingestion
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: full-ingestion
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16.x
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - run: npm ci
        - run: npm run lint && npm run prettier